name: NPM Auto Deprecate

on:
    schedule:
        - cron: '0 0 * * *'

jobs:
    auto-deprecate:
        name: NPM Auto Deprecate
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Project
              uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4
            - name: Use Node.js v18
              uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4
              with:
                  node-version: 18
                  cache: yarn
                  registry-url: https://registry.npmjs.org/
            - name: Install Dependencies
              run: yarn --immutable
            - name: Deprecate versions
              run: true || yarn npm-deprecate
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
